version: '3'
services:
  
  traefik:
    container_name: traefik
    image: traefik:v2.4
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  todo-list:
    container_name: todo-list
    build: ../../apps/todo-list
    ports:
      - "3000:3000"

  cats:
    container_name: cats
    build: ../../apps/flask-app
    ports:
      - "5000:5000"