services:

  wordpress:
    container_name: wordpress
    image: wordpress
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: lemonron
      WORDPRESS_DB_PASSWORD: supersecurepassword
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ../../apps/wordpress/html:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: lemonron
      MYSQL_PASSWORD: supersecurepassword
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ../../apps/wordpress/db:/var/lib/mysql

  cats:
    container_name: cats
    build: ../../apps/flask-app
    ports:
      - "5000:5000"

  nginx:
    container_name: nginx
    hostname: nginx
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ../static-content:/etc/nginx/html:ro
      - ../config/nginx_v2.9.conf:/etc/nginx/nginx.conf:ro