services:

  todo-list:
    container_name: todo-list
    build: ../../apps/todo-list
    ports:
      - "3000:3000"

  bulletin-board:
    container_name: bulletin-board
    build: ../../apps/bulletin-board
    ports:
      - "4000:8080"

  cats:
    container_name: cats
    build: ../../apps/cats
    ports:
      - "5000:5000"