services:

  nginx:
    container_name: nginx
    hostname: nginx
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ../static-content:/usr/share/nginx/html:ro
      - ../config/nginx.conf:/etc/nginx/nginx.conf:ro

  bulletin-board-app:
    container_name: bulletin-board-app
    build: ../../apps/bulletin-board-app
    ports:
      - "8080:8080"

  cats:
    container_name: cats
    build: ../../apps/flask-app
    ports:
      - "5000:5000"